--- 
abstract: A POE::Component::IRC plugin that provides blowfish encryption.
author: Johannes Plunien
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-IRC-Plugin-Blowfish
no_index: 
  directory: 
    - inc
    - t
requires: 
  Crypt::Blowfish_PP: 1.12
  POE: 0.37
  POE::Component::IRC: 5.07
version: 0.01
